# Generated by Django 4.0.2 on 2022-02-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_room_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_players',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('room_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.room')),
            ],
        ),
    ]
