# Generated by Django 4.0.2 on 2022-02-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_room_num_players_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='ABCD', unique=True),
            preserve_default=False,
        ),
    ]
