# Generated by Django 4.0.2 on 2022-02-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='room_code',
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.CharField(default='ABCD', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='num_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(default='ABCD', unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
